version: '3'
services:

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php-fpm_me
    # user: www-data
    user: root
    # ports:
    #   - 9000:9000
    restart: always
    working_dir: /var/www/html/
    volumes:
      - ./www:/var/www/html
      - "./php/php.ini:/usr/local/etc/php/php.ini"
    networks:
      - me-network

  nginx:
    image: nginx:1.26.0
    container_name: nginx_me
    # user: root
    ports:
      - 50001:80
    restart: always
    working_dir: /var/www/html/
    volumes:
      - ./www:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - me-network

  redis:
    image: redis:7
    container_name: redis_me
    restart: unless-stopped
    user: root
    tty: true
    # ports:
    #   - "63790:6379"
    networks:
      - me-network
    command: [ 'redis-server', '/etc/redis/redis.conf' ]
    volumes:
      - "./redis/redis.conf:/etc/redis/redis.conf"
      - "./redis/data:/data" 

  # MySQL Service
  mysql:
    image: mysql:8.0.26
    container_name: mysql8_me
    restart: unless-stopped
    user: root
    tty: true
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: web1
      MYSQL_ROOT_PASSWORD: dD704562006!
      TZ: Asia/Shanghai
    networks:
      - me-network
    volumes:
      - "./mysql8/data:/var/lib/mysql"
      - "./mysql8/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
      - "./mysql8/my.cnf:/etc/mysql/my.cnf"

# Docker Networks
networks:
  me-network:
    driver: bridge
